[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
acpi = "5.2.0"
arm-gic = "0.4.0"
bitflags = "2.9.1"
limine = "0.4.0"
spin = "0.10.0"

[build-dependencies]
bindgen = "0.71.1"
