[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
bitflags = "2.9.1"
good_memory_allocator = "0.1.7"
limine = "0.4.0"
pci_types = "0.10.0"
spin = "0.10.0"

[dependencies.crossbeam-queue]
version = "0.3.11"
features = ["alloc"]
default-features = false

[dependencies.virtio-drivers]
path = "crates/virtio-drivers"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.15.2"

[target.'cfg(target_arch = "aarch64")'.dependencies]

[build-dependencies]
bindgen = "0.71.1"
